// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"UITheme","status":true,"description":"UI 테마 (에디터 관리)","parameters":{}},
{"name":"BattleDebugPanel","status":true,"description":"전투 디버그 패널 — 전투화면 우측 상단에 디버그 버튼 표시","parameters":{}},
{"name":"EnemyHPBar","status":true,"description":"적 체력바 표시 (지연 감소 + 버프/디버프 아이콘)","parameters":{"barHeight":"10","barOffset":"6","iconSize":"22","maxIcons":"10","delaySpeed":"0.6"}},
{"name":"CustomSceneEngine","status":true,"description":"커스텀 씬 엔진 (에디터 관리)","parameters":{}},
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"on"}},
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"SkyBox","status":true,"description":"Three.js SkySphere - 3D 모드에서 파노라마 하늘 배경 표시","parameters":{"Skybox Folder":"skybox","Panorama File":"sky_panorama.png"}},
{"name":"TitleCredit","status":true,"description":"타이틀 화면에 Credit 버튼 추가","parameters":{"textFile":"data/Credits.txt"}},
{"name":"WASD_Movement","status":true,"description":"WASD 키로 이동, Q/E 키로 PageUp/PageDown 매핑","parameters":{}},
{"name":"TouchDestAnimation","status":true,"description":"터치/클릭 목적지에 RPG Maker 애니메이션 재생","parameters":{"Animation ID":"0","Hide Default":"true","Show Path Arrow":"true","Arrow Color":"rgba(255, 255, 255, 0.7)","Arrow Width":"3","Arrow Outline":"true","Arrow Outline Color":"rgba(0, 0, 0, 0.5)","Arrow Outline Width":"2","Show Destination Indicator":"true","Show Hover Highlight":"true"}},
{"name":"OcclusionSilhouette","status":true,"description":"플레이어가 오브젝트 뒤에 가려졌을 때 실루엣으로 위치를 표시합니다.","parameters":{"Fill Color":"#0040ff","Fill Opacity":"0.35","Outline Color":"#fd6d6d","Outline Opacity":"0.8","Outline Width":"1","Pattern":"diagonal","Pattern Scale":"8","Include Followers":"false"}},
{"name":"TouchCameraControl","status":true,"description":"","parameters":{"Drag Threshold":"12","Rotation Speed":"0.3","Tilt Min":"20","Tilt Max":"80","Zoom Min":"0.5","Zoom Max":"3.0","Zoom Speed":"0.01","Mouse Wheel Zoom":"true","Wheel Zoom Speed":"0.1"}},
{"name":"NPCNameDisplay","status":true,"description":"이벤트 캐릭터 머리 위에 NPC 이름을 표시합니다.","parameters":{"Font Size":"16","Text Color":"#ffffff","Outline Color":"rgba(0,0,0,0.85)","Outline Width":"3","Offset Y":"-4","Minimap Icon Mode":"editor"}},
{"name":"TextLog","status":true,"description":"텍스트 로그 - 메시지 대사 기록을 스크롤하며 볼 수 있는 창","parameters":{"menuName":"텍스트 로그","maxLines":"300","entryGap":"6","showFace":"true","faceSize":"100","bgOpacity":"160","scrollSpeed":"4"}},
{"name":"VisualNovelMode","status":true,"description":"비주얼 노벨 모드 - 화면 상단부터 텍스트를 누적 출력하는 VN 스타일 메시지 시스템","parameters":{"overlayOpacity":"120","transitionFrames":"24","textAreaX":"60","textAreaY":"40","textAreaWidth":"700","textAreaHeight":"520","choiceStyle":"inline","speakerColor":"#ffe066","choiceIndicator":">","autoExitDelay":"30","showScrollBar":"false"}},
{"name":"BuildVersion","status":true,"description":"타이틀 화면 오른쪽 하단에 빌드 번호를 표시합니다.","parameters":{"fontSize":"14","textColor":"rgba(255,255,255,0.5)","marginRight":"12","marginBottom":"8"}},
{"name":"AutoSave","status":true,"description":"오토 세이브 (자동 저장) 기능","parameters":{"enableMapTransferSave":"true","enableAfterBattle":"true","enableOnVariableChange":"false","variableChangeDelay":"500","enableAfterMenu":"true","slotLabel":"오토 세이브","showNotification":"true","--- 자동 저장 조건 ---":"","--- 표시 설정 ---":"","saveCooldown":"30"}},
{"name":"EnemyBook","status":true,"description":"적 도감","parameters":{"Unknown Data":"??????","Show In Menu":"true","Menu Text":"몬스터 도감"}},
{"name":"ItemBook","status":true,"description":"아이템 도감","parameters":{"Unknown Data":"??????","Price Text":"가격","Equip Text":"장비","Type Text":"타입","Show In Menu":"true","Menu Text":"아이템 도감"}},
{"name":"ShopStock","status":true,"description":"상점 재고 관리 - 상품별 재고, 동적 증감, 상품 추가/제거 지원","parameters":{"soldOutText":"품절","soldOutStatusText":"품절입니다.","soldOutColor":"#e04040","stockPrefix":"재고:","lowStockColor":"#ffaa00","noFundsText":"돈이 부족합니다.","noFundsColor":"#ffcc00"}},
{"name":"MessageWindowCustom","status":true,"description":"","parameters":{"windowWidth":"0","windowRows":"4","fontSize":"28","padding":"18","opacity":"255","frameOpacity":"255","backOpacity":"192","toneR":"0","toneG":"0","toneB":"0","windowskinName":"Window","windowX":"auto","windowY":"auto"}},
{"name":"MenuTransition","status":true,"description":"메뉴/UI 씬 배경 전환 효과 애니메이션","parameters":{"effect":"blur","blur":"20","overlayColor":"0,0,0","overlayAlpha":"100","duration":"40","easing":"easeOut","closeAnim":"true","transitionEffect":"scanline","blur_amount":"80","zoomBlur_amount":"80","zoomBlur_zoom":"50","desaturation_amount":"100","sepia_amount":"100","brightness_amount":"80","darkness_amount":"80","contrast_amount":"70","hue_amount":"60","invert_amount":"100","pixelation_amount":"80","zoom_amount":"60","chromatic_offset":"80","chromatic_alpha":"70","vignette_amount":"80","vignette_range":"50","scanline_opacity":"70","scanline_desaturation":"60"}},
{"name":"Minimap","status":true,"description":"미니맵 — FoW, 리전 색상, 2D/3D 지원","parameters":{"showOnStart":"false","shape":"circle","size":"160","margin":"10","opacity":"210","rotation":"north_fixed","tileSize":"4","viewRadius":"6","fowEnabled":"true","bgColor":"#1a2030","wallColor":"#445566","floorColor":"#7799aa","playerColor":"#ffffff","eventMarkerColor":"#ffcc00","showEvents":"true","regionColors":"{\"1\":\"#ff4444\",\"2\":\"#44cc44\",\"3\":\"#4488ff\",\"4\":\"#ffaa00\",\"5\":\"#cc44cc\"}","terrainColors":"{\"1\":\"#226633\",\"2\":\"#5588aa\",\"3\":\"#887766\",\"4\":\"#aaaaaa\",\"5\":\"#ffeecc\"}","borderColor":"#aabbcc","borderWidth":"2","iconFixedSize":"true","showMapName":"true","mapNameFontSize":"13","mapNameFont":"","mapNameColor":"#ffffff","mapNamePosition":"bottom","resetNameOnTransfer":"true"}},
{"name":"ImageCacheManager","status":true,"description":"이미지 캐시를 제어합니다. 용량·정리 주기 조정 및 캐시 완전 비활성화(MZ 방식) 지원.","parameters":{"cacheMode":"disabled","imageCacheLimit":"10","cleanupInterval":"30"}}
,
{"name":"QuestSystem","status":true,"description":"유연한 퀘스트 시스템","parameters":{"journalKey":"J","showTracker":"true","trackerX":"0","trackerY":"0","trackerWidth":"300","autoGiveRewards":"true"}},
{"name":"FlexibleJobs","status":true,"description":"유연한 직업 시스템","parameters":{"subClassSlots":"2","subStatRate":"50","subExpRate":"50","jpPerBattle":"10","jpPerLevel":"50","jpName":"JP","cmdClassChange":"전직","cmdSkillLearn":"스킬 습득"}},
{"name":"PuzzleSliding","status":true,"description":"슬라이딩 퍼즐 미니게임","parameters":{}},
{"name":"PuzzleLightsOut","status":true,"description":"Lights Out 스위치 퍼즐 미니게임","parameters":{}},
{"name":"PuzzleSokoban","status":true,"description":"소코반 박스 밀기 퍼즐 미니게임","parameters":{}},
{"name":"PuzzleLock","status":true,"description":"잠금장치 조합 퍼즐 미니게임","parameters":{}},
{"name":"PuzzleSimon","status":true,"description":"기억 게임(Simon Says) 미니게임","parameters":{}},
{"name":"PuzzlePipe","status":true,"description":"파이프 연결 퍼즐 미니게임","parameters":{}},
{"name":"PuzzleIce","status":true,"description":"얼음 미끄럼 퍼즐 미니게임","parameters":{}}
];